default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :build do
    xcodebuild(
      clean: true,
      build: true,
      scheme: "YandexMoneyCoreApiExampleFull",
      workspace: "YandexMoneyCoreApi.xcworkspace",
      xcargs: "CODE_SIGN_IDENTITY=\"\" CODE_SIGNING_REQUIRED=\"NO\""
    )
  end
end
